language: node_js
node_js:
  - 12
deploy:
  provider: heroku
  app: www-dopltechnologies-com
  on: main
  api_key:
    secure: pubmp64o5VuZARbPx3S49FmIlVSY1SxPpqqOYtnRuMgahrc8J2zqWdOEFHqHLSpUBPyK5R4TvHcJn7m3O5Hacrth8KbH7MpKbPvhp+R98Xx87s6gg1EGCDGOOKUNp8XOPfUFPEjTdA2lCGrlA9wW5NP49QZLS0f696Y60jEBgl7DOdOuizdOp29hqUjbMYMmRkSL3dVvEhauWf/bH/CXJHGoXUBwhxRHyuAbRkn552N5rZ+7KSBTIN9TGrwD+joR4xhdwlaXbGkIB25FBHYxVlefSW4ZFMAMyuQkm3Tuk5BKF2GbjR9FrUhRIVSX1/8C3FHVVRzHYDLCGHZW4oIA91+s/F7JAgSqYTqDbrjuT2e7ApoeiChgYs6CqkKyu48Z8+qZG7+8PdWbUB2vNBPvF/u13LtQPwMdhjld6B63EWe8JT0mDOJl1TStzUxvuPxwMErPgOau6Ty7lThTTNhgfmWQ6sXzOI508eh0fdl1V2IojwyTAC4RkP9kNG7TZl9XQj5ZO1BfLqE7NevwZAvFWWV8gnP2lAvU+WxGoMpGNfgJxEaBoIGFo8pMorEcb0CpRMY27P8jw9Im+CorAyVjIAcerEK1/c8TTUvRfTHTOl1Guo5UqQFkvCIyFEzXerq1+uZH8CvZUwBeKi57ZZjUiOnt1hnovH4dFYzzTU2dyz8=
